### ISSUE TITLE
parse.rb:23:in `source': undefined method `search' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by adarrra** [seanhagen/enex-to-markdown#1]
Hi! I have this error:
`parse.rb:23:in `source': undefined method `search' for nil:NilClass (NoMethodError)
	from parse.rb:33:in `parts'
	from parse.rb:39:in `block in parse'
	from /var/lib/gems/1.9.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
	from /var/lib/gems/1.9.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
	from /var/lib/gems/1.9.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
	from parse.rb:38:in `map'
	from parse.rb:38:in `parse'
	from parse.rb:74:in `run'
	from parse.rb:84:in `<main>'
`
Can you help?

**Comment by seanhagen** [comment]
Hey adarra, thanks for the bug report. I'll try to look into this in the next week.
